#####################################################
#                 HOLIDAYS 8.0                      #
#####################################################

templates:
  Holiday:
    sort_title: zzzzzzzzzz_<<collection_name>>
    smart_label: random
    sync_mode: sync
    visible_home: false

# Holiday collections that will show up when the holiday has started and disappear when it has ended
collections:
  Natal ğŸ„:
    template: { name: Holiday }
    visible_home: range(12/01-12/27)
    visible_shared: range(12/01-12/27)
    summary: Ho ho ho.
    file_poster: config/posters/Christmas.png
    trakt_list:
      - https://trakt.tv/users/ad76/lists/hallmark-christmas?sort=released,asc
      - https://trakt.tv/users/k0meta/lists/christmas-extravaganza-non-tv-movie
      - https://trakt.tv/users/movistapp/lists/christmas-movies
      - https://trakt.tv/users/questdvd/lists/absolute-hayes-christmas-classics
      - https://trakt.tv/users/littlestella3/lists/christmas

  PÃ¡scoa ğŸ£:
    template: { name: Holiday }
    visible_home: range(03/31-04/30)
    visible_shared: range(03/31-04/30)
    summary: The Easter bunny is here!
    file_poster: config/posters/Easter.png
    trakt_list:
      - https://trakt.tv/users/smwixted/lists/easter?sort=votes,asc
      - https://trakt.tv/users/tarzanislav/lists/easter?sort=added,asc
      -
  25 de Abril ğŸŒ¹:
    template: { name: Holiday }
    visible_home: range(04/24-04/26)
    visible_shared: range(04/24-04/26)
    summary: Liberdade!
    file_poster: config/posters/25thApril.png
    trakt_list:
      - https://trakt.tv/users/caldeirag/lists/25-de-abril?sort=rank,asc

  Dia do Pai ğŸ‘¨â€ğŸ‘¦:
    template: { name: Holiday }
    visible_home: range(03/14-03/23)
    visible_shared: range(03/14-03/23)
    summary: Every Fathers Special day.
    file_poster: config/posters/Fathers Day.png
    trakt_list:
      - https://trakt.tv/users/fcisco13/lists/dad-movies?sort=rank,asc
      - https://trakt.tv/users/segfaulted/lists/movies-for-dad?sort=rank,asc

  Halloween ğŸƒ:
    template: { name: Holiday }
    visible_home: range(10/01-10/31)
    visible_shared: range(10/01-10/31)
    summary: This is Halloween!
    file_poster: config/posters/Halloween..png
    trakt_list:
      - https://trakt.tv/users/29zombies/lists/halloween
      - https://trakt.tv/users/galacticboy/lists/not-so-spooky-halloween
      - https://trakt.tv/users/kairbear08/lists/halloween
      - https://trakt.tv/users/mybicycle/lists/halloween

  Dia da MÃ£e ğŸ‘©â€ğŸ‘§:
    template: { name: Holiday }
    visible_home: range(05/01-05/31)
    visible_shared: range(05/01-05/31)
    summary: Every Mothers special day.
    file_poster: config/posters/Mothers Day.png
    trakt_list:
      - https://trakt.tv/users/movie-pal/lists/mother-s-day?sort=rank,asc
      - https://trakt.tv/users/mdm144/lists/mother-s-day?sort=rank,asc

  Novo Ano ğŸ¾:
    template: { name: Holiday }
    visible_home: range(12/30-01/05)
    visible_shared: range(12/30-01/05)
    summary: Happy New Year!
    file_poster: config/posters/New Year.png
    trakt_list:
      - https://trakt.tv/users/gullibletransport/lists/new-year?sort=random,asc
      - https://trakt.tv/users/sympli/lists/new-years-movies?sort=rank,asc
      - https://trakt.tv/users/padawan_seneca/lists/new-years-eve?sort=rank,asc
      - https://trakt.tv/users/galacticboy/lists/new-years?sort=rank,asc

  Dia de SÃ£o Valentim ğŸ’˜:
    template: { name: Holiday }
    visible_home: range(02/13-02/15)
    visible_shared: range(02/13-02/15)
    summary: Love me tender, love me sweet.
    file_poster: config/posters/Valentines Day.png
    trakt_list:
      - https://trakt.tv/users/movie-pal/lists/valentine-s-day
      - https://trakt.tv/users/barsaky/lists/den-svateho-valentina-valentine-s-day
      - https://trakt.tv/users/abbelea/lists/movies-best-of-love
